services:
  gotify:
    image: gotify/server:latest
    pull_policy: always
    container_name: gotify
    restart: unless-stopped
    ports:
      - "80"
    environment:
      GOTIFY_DATABASE_DRIVER: postgres
      GOTIFY_DATABASE_CONNECTION: "host=postgres user=gotify password=gotify dbname=gotify sslmode=disable"
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS}
      GOTIFY_SERVER_PORT: 80
      GOTIFY_SERVER_SSL_REDIRECT: "false"
      GOTIFY_SERVER_KEEPALIVE_PERIOD_SECONDS: 0
      GOTIFY_SERVER_WEBSOCKET_ORIGIN: ${GOTIFY_SERVER_WEBSOCKET_ORIGIN}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.2
    container_name: gotify-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gotify
      POSTGRES_USER: gotify
      POSTGRES_PASSWORD: gotify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gotify -d gotify"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: